apiVersion: apps/v1
kind: Deployment
metadata:
  name: order bc
  labels:
    app: order bc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order bc
  template:
    metadata:
      labels:
        app: order bc
    spec:
      containers:
        - name: order bc
          image: "username/order bc:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
